### ISSUE TITLE
Middle points are not on the line

### ISSUE THREAD

**Issue by mahmoudmy** [Leaflet/Leaflet.Editable#64] opened 2016-03-02 06:21 UTC
Some times when I enable editing on lines, the middle (inactive) point are far from main line!
![map](https://cloud.githubusercontent.com/assets/5320237/13452349/3d569b20-e05c-11e5-8cb3-ad289435c68c.png)

**Comment by yohanboniface** [comment] 2016-03-02 16:02
Can you make a simple reproducible test case?

**Comment by mahmoudmy** [comment] 2016-03-05 06:14
I'm using Leaflet in an Angular app via [ui-leaflet](https://github.com/angular-ui/ui-leaflet) directive:
``` javascript
var myLine = a_geojson_LineString_Feature;  // a geojson feature with geometry.type = 'LineString'
var editableLayers = new L.featureGroup();

leafletData.getMap().then(function(map) {
  map.addLayer(editableLayers);
  var _coord = myLine.geometry.coordinates;
  var newCoordinates = [];
  _coord.forEach(function(item) {
    var _newPoint = [item[1], item[0]];
    newCoordinates.push(_newPoint);
  });
  myLine = L.polyline(newCoordinates, {
    color: 'blue'  // I use a function for this in my code
  }).addTo(editableLayers);
  myLine .enableEdit();
  map.fitBounds(editableLayers.getBounds());
});
```
Thanks for your comments.

**Comment by yohanboniface** [comment] 2016-03-05 06:25
H same code without any Angular or whatever magic?

**Comment by mahmoudmy** [comment] 2016-03-05 07:21
No, I just tried with Angular!
Here is a live example: https://jsfiddle.net/pjk1zkca/2/ .

But Why middle point does not appear on loading?

**Comment by onyedikilo** [comment] 2016-07-24 21:17
It has something to do with the zoom levels, for a quick fix; 
I updated your plunker example https://jsfiddle.net/pjk1zkca/5/
If you load the lines or polygons with a zoomed out map then something gets screwed up with the control points. If you zoom in and then load something, everything works fine.

**Comment by onyedikilo** [comment] 2016-07-24 21:47
I changed the computeLatLng function for L.Editable.middleMarker: (around line 423), I think the problem is with the latLngToContainerPoint conversations, its returned value changes with the zoom level. The below change seems to work fine;

`computeLatLng: function () {
        var lat = (this.left.latlng.lat + this.right.latlng.lat) / 2;
        var lng = (this.left.latlng.lng + this.right.latlng.lng) / 2;
        return L.latLng(lat, lng);
    }, `

**Comment by mahmoudmy** [comment] 2016-07-25 05:29
Very Nice!
Please submit a pull request.

**Comment by onyedikilo** [comment] 2016-07-25 10:03
Tried but, it seems that I don't have permission to create a pull request.

**Comment by yohanboniface** [comment] 2016-08-28 15:49
Closing as not reproducible.
Please reopen if you can come up with a reproducible test case with latest versions and not external deps (http://playground-leaflet.rhcloud.com/ is your friend for that).

**Closed by yohanboniface** 2016-08-28 15:49 UTC

**Comment by yohanboniface** [comment] 2016-08-28 15:51
Also note that position is computed in pixel space because of #4 (see also https://github.com/Leaflet/Leaflet.Editable/commit/f04b2f611053e9eb7e169dda859a57ad2da29281).
