### ISSUE TITLE
Events for rectangle and circle drawing are inconsistent with polygon drawing events

### ISSUE THREAD

**Issue by xoqem** [Leaflet/Leaflet.Editable#89] opened 2016-08-09 01:17 UTC
When drawing a polygon, the events editable:drawing:commit and editable:drawing:end fire once the user has drawn and finalized their shape, as expected.  When drawing a circle or rectangle, these events both fire on mouse down, and then events for dragging start firing, as if the shape were created then dragged.  Ideally, the circle and rectangle drawing modes wouldn't commit/end the drawing until the user has released the mouse button and the shape is finalized, to allow for consistent implementation when handling user shape drawing.

As an aside, the workaround I used was to listen for the event editable:vertex:dragend which fired after the user finished sizing the rectangle and circle.  Though the downsides to this was if the user clicked when drawing a square, but never dragged that event never fired (though I was able to hack around that with a mouse up listener, and checking state in my app).

My use case is basically: I listen for editable events when the user makes a shape, I grab that shape, do some things with it and add its geojson to another layer I'm maintaining.  Then I clear the editable layer for their next drawing.  This works great, with the exception of having to rig up the events differently for polygons vs rectangles and circles.

**Comment by yohanboniface** [comment] 2016-08-09 07:03
Duplicate of #70 
The tricky part being that the rectangle is actually created on first click *then* edited.
I understand that the behaviour seems inconsistent, so I'd like to change that, but that's not easy.

**Closed by yohanboniface** 2016-08-09 07:03 UTC

**Comment by xoqem** [comment] 2016-08-09 22:43
Hey, thanks for the response, apologies for sending the duplicate.  I have a fix for the rectangle drawing mostly done, working on the circle now.  Will send a PR your way that you are welcome to use when I finish.  Thanks!
