### ISSUE TITLE
Rectangle drawing only allows for dragging from top left corner only

### ISSUE THREAD

**Issue by xoqem** [Leaflet/Leaflet.Editable#90] opened 2016-08-09 01:21 UTC
It'd be nice if the rectangle could be dragged in any direction with the initial point staying fixed (like the circle).  However, right now, once the initial point is set, the rectangle can only be dragged from the top left corner down and to the right.  Dragging the other way moves the initial point.  Not a huge deal, a user eventually figures out what is going on, but it would be nice if dragging to the right or to the top of the initial point didn't move the initial point, but just made the rectangle in that direction.

**Comment by yohanboniface** [comment] 2016-08-09 07:00
Duplicate of #87

**Closed by yohanboniface** 2016-08-09 07:00 UTC

**Comment by xoqem** [comment] 2016-08-09 22:44
Hey, thanks for the response, apologies for sending the duplicate.  I have a fix for this that seems to work well.  Will send a PR your way that you are welcome to use when I finish.  Thanks!
