### ISSUE TITLE
Executing function in "editable:created" event

### ISSUE THREAD

**Issue by flightsurvey** [Leaflet/Leaflet.Editable#111] opened 2016-11-11 22:50 UTC
I want to be able to store the polygon definitions in a database and so have evolved the following workflow:

```js
map.on('editable:created', function (e) {
  getNewPolygonID(e.layer);
});

function getNewPolygonID(layer) {

  vUrl = '../libs/php/getNewPolygonID.php';

  $.ajax({
     url: vUrl,
     type: 'GET',
     dataType: 'json',
     success: function (data) {
        layer._leaflet_id = data.polygonID;
        layer.bindPopup("ID: " + data.permissionID);
     },
     error: function(jqXHR, textStatus, errorThrown) {
       console.log(textStatus, errorThrown);
     }
  }); 

}
```
getNewPolygonID.php creates a new row in a MYSQL table and returns it's id.

Finally, an event on "editable:disable" iterates through the layers and updates the database.

Unfortunately, the code in "editable:created" event appears to interfere with the drawing and deleting of subsequent polygons. Some won't draw correctly and others, on deleting, leave some elements of the polygon still on screen. If I remove the code in the "editable:created" event then the polygons can be created, modified and deleted as expected.

**Addendum:** 

I should have added that the console generates an error: 
"Uncaught TypeError: Cannot read property 'ctrlKey' of undefined"

which refers to the following code:
```
var deleteShape = function (e) {

  if ((e.originalEvent.ctrlKey || e.originalEvent.metaKey) && this.editEnabled()) {

    this.editor.deleteShapeAt(e.latlng);

  }

};

map.on('layeradd', function (e) {

  if (e.layer instanceof L.Path) e.layer.on('dblclick', L.DomEvent.stop).on('dblclick', e.layer.toggleEdit);

});
```

**Another Addendum**

I think that it might be the line in the ajax success adding the popup that causes the problem. If I remove this then things work a little better. Some polygons just won't completely delete though and I've tried it in the latest versions of FF and Chrome wit the same result.

**Comment by yohanboniface** [comment] 2016-11-12 08:39
>  "Uncaught TypeError: Cannot read property 'ctrlKey' of undefined"

Means just that: you are calling `deleteShape` with an event that does not contains the key originalEvent.

I'm closing here because I don't think it's a Leaflet.Editable issue. Feel free to reopen if you can provide a minimal test case reproducing the issue, without other dependencies, with http://playground-leaflet.rhcloud.com/ for example.

**Closed by yohanboniface** 2016-11-12 08:39 UTC
